Allow passing in memoize functions directly to `createSelector`.
reduxjs/reselect pull request #626
Opened 2023-09-30 05:02 UTC by aryaemami59

This PR solves the issue of having to call `createSelectorCreator` anytime we want to use an alternate memoizer. You can now pass in the memoizer function directly to `createSelector`. So it looks something like this:

```ts
const selectorAutotrack = createSelector(
      (state: State) => state.todos,
      todos => todos.map(t => t.id),
      { memoizeMethod: autotrackMemoize }
    )
```

The runtime implementation wasn't really difficult, the main issue was getting TypeScript to recognize that if we pass in a function to `memoizeMethod`, then the type of `memoizeOptions` has to dynamically change to whatever the type of options args are in `memoizeMethod`. Here is an example:

```ts
const createSelectorWeakMap = createSelectorCreator(weakMapMemoize)
// This would result in a TS error.
const selector1 = createSelectorWeakMap(
    (state: State) => state.todos,
    todos => todos.map(t => t.id),
    { memoizeOptions: { maxSize: 2 } }
  )
  
// This on the other hand is fine.
const selector2 =
    createSelectorWeakMap(
      (state: State) => state.todos,
      todos => todos.map(t => t.id),
      { memoizeMethod: defaultMemoize, memoizeOptions: { maxSize: 2 } } // When memoizeMethod is changed to defaultMemoize, memoizeOptions can now be the same type as options args in defaultMemoize.
    )
```

Just to make sure everything is now working as expected, I tested both the types and runtime behavior in my personal projects using yalc. Hope this helps, please let me know if anything else is needed.

2023-10-05 15:12 UTC, markerikson commented
Thanks, I'll try to look at this over the weekend!

2023-10-24 19:29 UTC, markerikson commented
fyi this is still on my list to review, but was at a conf last week and am also trying to sort out a couple other outstanding RTK PRs before I switch over to look at this.

2023-10-24 19:35 UTC, aryaemami59 commented
> fyi this is still on my list to review, but was at a conf last week and am also trying to sort out a couple other outstanding RTK PRs before I switch over to look at this.

Not a problem at all, I know you're busy. I'm just trying to make everything easier for you to review so hopefully you can merge without any issues. Is there anything specific you would want me to do before you get a chance to review it? I'd be happy to help.

2023-10-24 19:38 UTC, markerikson commented
Nothing I can think of immediately, other than "fix the TS types so they compile" :)

2023-10-24 19:39 UTC, aryaemami59 commented
> Nothing I can think of immediately, other than "fix the TS types so they compile" :)

Oh shoot. My apologies, I will fix that right away.

2023-10-28 17:36 UTC, markerikson commented
I've updated `master` to run the RTK CI example app tests against the latest RTK betas on `rtk/v2.0-integration`, and dropped support for TS <4.7.  Rebased this PR against `master` to pick those up.

Now trying to actually get a sense of what all's changed in this PR :)

2023-10-28 18:54 UTC, markerikson requested changes

2023-10-28 18:55 UTC, markerikson commented
Initial thoughts:

- I like refactoring the codebase to move all the definitions out of `index.ts`, and leaving that as just the package exports
- The JS logic seems reasonable
- I _really_ appreciate all the added JSDoc comments on all the types!
- I haven't fully grokked or followed through on all the TS types changes, but things seem to make sense overall
- I _love_ the additional type, unit, and perf tests!  Even without reading them carefully, that gives me a lot of confidence that your changes are working as intended.

In fact, I think I've really only got two bits of feedback:

First, per review comment, the `process.env.NODE_ENV` check needs to be at the parent function level to make sure this code gets eliminated during the prod build step

The other one's trickier, and has to do with user DX for TS/VS Code hover previews.

As an example: if you look at `typescript_test/test.ts` around line 1268, we've got this call:

```ts
  const selector = createSelector(
    (state: { foo: string }) => 1,
    (state: { bar: string }) => 2,
    (...args) => 0
  )
```

Currently, the TS hover preview looks like this:

![image](https://github.com/reduxjs/reselect/assets/1128784/445143b3-acf1-4c5e-bc2c-4e52620b27e1)

It's a bit annoying (especially with the double `{clearCache()}` in there), but it shows you it's a function that takes an object as an argument.

With this PR, the preview is:

![image](https://github.com/reduxjs/reselect/assets/1128784/c1b4f95c-1e53-4bdb-a1c0-0b0cc9915691)

which is a lot more verbose and doesn't even _look_ like a function at all.

Ideally, I'd want to see something akin to (made up):

```ts
const selector: (state: {foo: string, bar: string}) => number
  & {clearCache: () => void, recomputations: () => void, .......}
```

In other words, a more human-readable representation that "this is a function with these args, and also has these fields attached".

I have some long-left-over TS util types in `types.ts` that are supposed to convince TS to expand types: `Expand<T>`, `ExpandRecursive<T>`, `ComputeDeep<T>`, and `Mapped<T>`.  I spent a few minutes trying to play with them and insert them in various spots around `OutputSelector<T>`.  I was able to get the "it's just a function" part working, but that lost all knowledge of the attached selector fields.

I'm fine with merging this PR basically as-is (and I'll try to push the `process.env.NODE_ENV` changes myself shortly), but could you also take a stab at trying to get a more readable preview for selectors?

2023-10-28 19:23 UTC, markerikson approved these changes

2023-10-28 19:34 UTC, markerikson commented
Okay, this looks _amazing_!  Thank you!

I'm going to go ahead and merge this, then do a couple other bits of cleanup and put out `5.0.0-beta.0`.  

Let's do any hover preview changes and docs work in follow-up PRs.

2023-10-28 19:34 UTC, merged

2023-10-28 22:11 UTC, aryaemami59 commented
Thanks for all the feedback. I'm glad you mentioned the issue with the hover preview, because for the past couple of days, I've been looking for a way to simplify that as well. I will go ahead and submit PRs for some more JSDocs I was adding and the hover preview issue.

2023-10-28 22:15 UTC, markerikson commented
Yep! Also FYI, we're now in a bizarre cyclical dep issue because I renamed `autotrackMemoize` to `unstable_autotrackMemoize` and published that as Reselect 5.0.0-beta.0, but RTK beta tries to re-export `autotrackMemoize`, and so the CI examples are now failing since that export doesn't exist :)

I'm going to publish a new RTK beta shortly with fixes for this.

2023-10-29 20:09 UTC, aryaemami59 commented
I figured out how to solve the hover preview issue, but while doing so, I also (coincidentally) resolved the infinite type instantiation  issue. The problem is it looks like resolving the hover preview issue, causes the inifnite type instantiation problem (to some extent). So I'm going to figure out if there is a reasonable middleground to reach. Also fixed some type issues related to `createStructuredSelector`.

2023-10-30 02:12 UTC, aryaemami59 commented
![selector-hover](https://github.com/reduxjs/reselect/assets/86934138/165756be-ec07-4080-b8f9-ddff11f86517)

I tried really hard to get VSCode to show as much info as possible in the hover preview without sacrificing too much TS performance / type safety. Do you think this suffices? I'm gonna have another go at it in the next few days either way, I just wanted to get your feedback on it if possible.

2023-10-30 02:31 UTC, markerikson commented
@aryaemami59 that's certainly a step in the right direction!

It'd be nice if we could get `OutputSelectorFields` simpler in some way, but that at least has the most critical info visible.

2023-10-30 02:38 UTC, aryaemami59 commented
> @aryaemami59 that's certainly a step in the right direction!
> 
> It'd be nice if we could get `OutputSelectorFields` simpler in some way, but that at least has the most critical info visible.

I will try again some more tomorrow, but I did have one question, is there a reason why we have an overload for `createStructuredSelector`?

2023-10-30 02:40 UTC, markerikson commented
No idea, actually!

2023-10-30 02:54 UTC, aryaemami59 commented
> No idea, actually!

Yeah me neither, it doesn't make any sense. I'll see if I can get rid of it since the function itself has only one single behavior.